<?php
/** Владелец установки выбирает собственные опубликованные документы, не документы продавца темы. */
if ( ! current_user_can( 'manage_options' ) ) { return; }
$config = Ioblog_Legal_Settings::get();
$documents = array( 'privacy' => __( 'Personal data policy', 'ioblog-editorial' ), 'consent' => __( 'Separate personal-data consent', 'ioblog-editorial' ), 'disclosure' => __( 'Separate public-profile consent', 'ioblog-editorial' ) );
?>
<div class="wrap io-admin"><h1 class="screen-reader-text"><?php esc_html_e( 'Privacy and consent', 'ioblog-editorial' ); ?></h1><header class="io-admin-hero"><div><span>IO BLOG · PRIVACY</span><h2 class="io-admin-title"><?php esc_html_e( 'Privacy and consent', 'ioblog-editorial' ); ?></h2><p><?php esc_html_e( 'The site owner is responsible for personal-data processing. The theme provides technical controls, not legal certification.', 'ioblog-editorial' ); ?></p></div></header>
<?php if ( isset( $_GET['saved'] ) ) { ?><div class="notice notice-success"><p><?php esc_html_e( 'Settings saved.', 'ioblog-editorial' ); ?></p></div><?php } ?>
<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="io_legal_settings"><?php wp_nonce_field( 'io_legal_settings' ); ?>
<section class="io-admin-card"><h2><?php esc_html_e( 'Site documents', 'ioblog-editorial' ); ?></h2><p><?php esc_html_e( 'Create separate Gutenberg pages with your operator details, purposes, data categories, retention, withdrawal procedure and publication conditions. Have the wording reviewed before publishing. Drafts and password-protected pages cannot authorize registration.', 'ioblog-editorial' ); ?></p><div class="io-admin-grid io-admin-fields">
<?php foreach ( $documents as $kind => $label ) { ?><label><strong><?php echo esc_html( $label ); ?></strong><?php wp_dropdown_pages( array( 'name' => 'legal[' . $kind . '_page]', 'selected' => $config[ $kind . '_page' ], 'show_option_none' => __( 'Select a published page', 'ioblog-editorial' ), 'option_none_value' => 0, 'post_status' => 'publish' ) ); ?><small><?php echo Ioblog_Legal_Settings::page( $kind ) ? esc_html__( 'Document available', 'ioblog-editorial' ) : esc_html__( 'Document not configured', 'ioblog-editorial' ); ?></small></label><?php } ?>
<label><strong><?php esc_html_e( 'Consent revision', 'ioblog-editorial' ); ?></strong><input name="legal[revision]" value="<?php echo esc_attr( $config['revision'] ); ?>" maxlength="32" required><small><?php esc_html_e( 'Changing documents or this revision asks visitors to choose optional integrations again.', 'ioblog-editorial' ); ?></small></label></div></section>
<section class="io-admin-card"><h2><?php esc_html_e( 'Consent controls', 'ioblog-editorial' ); ?></h2><div class="io-admin-toggles">
<?php foreach ( array( 'notice_enabled' => __( 'Privacy notice and optional-code control', 'ioblog-editorial' ), 'require_consent' => __( 'Require separate consent for registration', 'ioblog-editorial' ) ) as $key => $label ) { ?><label class="io-admin-toggle"><input type="hidden" name="legal[<?php echo esc_attr( $key ); ?>]" value="0"><input type="checkbox" name="legal[<?php echo esc_attr( $key ); ?>]" value="1" <?php checked( $config[ $key ] ); ?>><span aria-hidden="true"></span><?php echo esc_html( $label ); ?></label><?php } ?></div><p class="description"><?php esc_html_e( 'Analytics snippets and all theme advertising slots stay inert until their category is allowed. Code from other plugins, manually embedded services, CAPTCHA and OAuth are outside this optional-code switch and must be assessed separately by the site owner.', 'ioblog-editorial' ); ?></p><p class="description"><?php esc_html_e( 'The notice is not registration consent. Public profiles require a separate publication document and explicit opt-in. A consent checkbox alone does not satisfy every obligation under Russian Federal Law 152-FZ.', 'ioblog-editorial' ); ?></p></section>
<?php submit_button(); ?></form></div>
